# 公共配置
spring:
  profiles:
    active: dev
  application:
    name: alibaba-nacos-provider
  servlet:
    multipart:
      # 最大支持文件大小
      max-file-size: 50MB
      # 最大支持请求大小
      max-request-size: 50MB

#开启端点  actuator
management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"  #开启actuator全部端点      http://IP:PORT/actuator
#mybatis plus
mybatis-plus:
  # xml文件扫描
  mapper-locations: classpath:mapper/order/*.xml,classpath:/mapper/**/*.xml #,classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xiaomai.cloud.po
  check-config-location: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #是否开启自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: false
    #全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存
    cache-enabled: true
    call-setters-on-nulls: true
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    #MyBatis 自动映射时未知列或未知属性处理策略 NONE：不做任何处理 (默认值), WARNING：以日志的形式打印相关警告信息, FAILING：当作映射失败处理，并抛出异常和详细信息
    auto-mapping-unknown-column-behavior: WARNING
  global-config:
    banner: false
    db-config:
      #uuid/none/input/id_worker/id_worker_str/auto   表示全局主键都采用该策略（如果全局策略和局部策略都有设置，局部策略优先级高）
      #主键类型  0:"数据库ID自增", 1:"未设置主键类型",2:"用户输入ID (该类型可以通过自己注册自动填充插件进行填充)", 3:"全局唯一ID (idWorker), 4:全局唯一ID (UUID), 5:字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: UUID
      #字段验证策略 IGNORED:"忽略判断", NOT_NULL:"非NULL判断", NOT_EMPTY:"非空判断", DEFAULT 默认的,一般只用于注解里(1. 在全局里代表 NOT_NULL,2. 在注解里代表 跟随全局)
      field-strategy: NOT_EMPTY
      #数据库大写下划线转换
      capital-mode: true
      #逻辑删除字段标识
      #logic-delete-field: flag
      #逻辑删除值
      logic-delete-value: 1
      #逻辑未删除值
      logic-not-delete-value: 0


---
# 开发环境
server:
  port: 10010
spring:
  profiles: dev
  servlet: /
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:48848
  # dynamic DataSource Config
  datasource:
    hikari:
      maximum-pool-size: 30
      minimum-idle: 1
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master，如果读者只是单数据源只需要注释掉slave相关配置即可，这里为了方便演示master与slave保持相同
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/db2020?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
          username: root
          password: mysql
        slave:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:13306/db2020?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
          username: root
          password: mysql
# Minio文件存储配置信息
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketNameHtml: html
  bucketNameImage: image

#==================== 日志配合·标准  ============================
#logging:
  #config: classpath:logback-boot.xml

#配置日志
#采用相对路径方式将日志文件输出到【log\myspringboot.log】

logging:
  #配置日志文件路径
  level:
    #项目日志
    com.xiaomai.coud : ERROR
    org.springfromework.web: ERROR
    #Excel工具日志（DEBUG、INFO、WARN、ERROR和FATAL）
    #com.github.liaochong.myexcel.core: ERROR
    com.baomidou.dynamic: debug
#接口文档开启
knife4j:
  enable: true



---
# 测试环境
server:
  port: 11010
spring:
  profiles: test
  servlet: /
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:48848

---
# 生产环境
server:
  port: 12010
spring:
  profiles: prod
  servlet: /
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:48848
#接口文档关闭
knife4j:
  production: true
