server:
  port: 10088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db2020?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    xa:
      properties:
        useInformationSchema: true
  #其中第一句是表示：当发现404异常时直接抛出异常。
  #第二句关闭默认的静态资源路径映射。这样404错误也能被捕获到，但是这个配置会让你的静态资源访问出现问题，也就是不适合前后端不分离的情况。
  mvc:
    #默认情况下，SpringBoot是不会抛出404异常的，所以@ControllerAdvice也不能捕获到404异常。我们可以通过以下配置来让这个注解能捕获到404异常。
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  #
  #@Configuration
  #public class ResourceConfig implements WebMvcConfigurer {
  #   @Override
  #    public void addResourceHandlers(ResourceHandlerRegistry registry) {
  #       //可以访问localhost:8095/static/images/image.jpg
  #        registry.addResourceHandler("/static/**").addResourceLocations("classpath:/static/");
  #    }
  #}
  # sa-token配置
  sa-token:
      # token名称（同时也是cookie名称）
      token-name: satoken
      # token有效期，单位s 默认30天，-1为永不过期
      timeout: 2592000
      # token临时有效期（指定时间内无操作视为token过期，单位为s）
      activity-timeout: -1
      # 是否允许同一账号并发登陆
      allow-concurrent-login: true
      # 在多人登录同一账号时，是否共享会话（为true时共用一个，为false时新登录挤掉旧登录）
      is-share: true
      # 是否在cookie读取不到token时，继续从请求header里继续尝试读取
      is-read-head: true
      #  是否在header读取不到token时，继续从请求题参数里继续尝试读取
      is-read-body: true
      # 是否在初始化配置时打印版本字符画
      is-v: true
      #默认uuid
      token-style: simple-uuid




#日志配置
logging:
  #pattern:
    #console: "%d{yyyy-MM-dd} [%thread] %-5level %logger{50} -%msg%n"
    #file: "%d{yyyy‐MM‐dd} === [%thread] === %‐5level === %logger{50} ==== %msg%n"
  file:
    #默认从项目根目录下开始
    path: log/
    name: mytestlog.log
  level:
    com.xiaomai.cloud: DEBUG
    # 通过设置root日志等级，更改所有包的日志级别 默认为INFO
    root: INFO



