# 公共配置
spring:
  profiles:
    active: dev
  application:
      name: nacos-webservice

#mybatis plus
mybatis-plus:
  # xml文件扫描
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xiaomai.cloud.po
  check-config-location: true
  configuration:
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #是否开启自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: false
    #全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存
    cache-enabled: true
    call-setters-on-nulls: true
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    #MyBatis 自动映射时未知列或未知属性处理策略 NONE：不做任何处理 (默认值), WARNING：以日志的形式打印相关警告信息, FAILING：当作映射失败处理，并抛出异常和详细信息
    auto-mapping-unknown-column-behavior: WARNING
  global-config:
    banner: false
    db-config:
      #uuid/none/input/id_worker/id_worker_str/auto   表示全局主键都采用该策略（如果全局策略和局部策略都有设置，局部策略优先级高）
      #主键类型  0:"数据库ID自增", 1:"未设置主键类型",2:"用户输入ID (该类型可以通过自己注册自动填充插件进行填充)", 3:"全局唯一ID (idWorker), 4:全局唯一ID (UUID), 5:字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: UUID
      #字段验证策略 IGNORED:"忽略判断", NOT_NULL:"非NULL判断", NOT_EMPTY:"非空判断", DEFAULT 默认的,一般只用于注解里(1. 在全局里代表 NOT_NULL,2. 在注解里代表 跟随全局)
      field-strategy: NOT_EMPTY
      #数据库大写下划线转换
      capital-mode: true
      #逻辑删除字段标识
      #logic-delete-field: flag
      #逻辑删除值
      logic-delete-value: 1
      #逻辑未删除值
      logic-not-delete-value: 0

---
server:
  port: 18080
spring:
  profiles: dev
  servlet: /
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  datasource:
    hikari:
      maximum-pool-size: 30
      minimum-idle: 1
    dynamic:
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/db2020?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
          username: root
          password: mysql

