server:
  port: 8888
spring:
  application:
    name: gateway-server
  main:
    allow-bean-definition-overriding: true #当遇到同样的名字时候，是否允许覆盖注册
  cloud:
    gateway:
     discovery:
        locator:
          enabled: true #开启自动路由,以服务id建立路由，服务id默认大写
          lower-case-service-id: true #服务id设置为小写
     routes:
        - id: gateway-test-route
          uri: https://www.12306.cn
          predicates:
            - Path=/gatewaytest/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@apiKeyResolver}"
                redis-rate-limiter.replenishRate: 1 #允许每秒处理多少个请求
                redis-rate-limiter.burstCapacity: 1 #允许在一秒钟内完成的最大请求数

        - id: alibaba-cloud-user
          uri: http://localhost:20010
          order: 666 #数字越小优先匹配
          predicates:
            - Path=/user/**
          filters:
            - name: AuthCheckFilter #会话验证
            - StripPrefix=1 #去掉前缀

        - id: alibaba-nacos-consumer
          uri: http://localhost:20010
          #uri: https://www.12306.cn
          predicates:
            - Path=/nacosconsumer/**
          filters: StripPrefix=1

        - id: alibaba-nacos-consumer-openfeign
          uri: lb://alibaba-nacos-consumer-openfeign
          predicates:
            - Path=/nacosconsumerfeign/**
          filters: StripPrefix=1

        - id: alibaba-nacos-provider
          uri: lb://alibaba-nacos-provider
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: fallbackname
                fallbackUri: forward:/myfallback
    nacos:
      discovery:
        server-addr: 127.0.0.1:48848
        #register-enabled: false
        #namespace:   #命名空间

    sentinel:
      filter:
        enabled: false #spring.cloud.sentinel.filter.enabled 配置项置为 false（若在网关流控控制台上看到了 URL 资源，就是此配置项没有置为 false）。
      transport:
        dashboard: localhost:8088
        client-ip: 127.0.0.1
        port: 8720
      # 服务启动直接建立心跳连接
      eager: true
      scg:
        fallback:
          mode: response
          response-status: 455
          response-body: error!
      datasource:
        ds1:
          nacos:
            server-addr: localhost:48848
            namespace: 3c5520b1-d16c-48a6-b2e1-129596f41b57
            dataId: gateway_sentinel
            group: DEFAULT_GROUP
            data-type: json
            rule-type: flow
  security:
    user:
      name: test
      password: 123456

  redis:
    host: localhost
    pool: 6379
    password: 123456
    database: 1
