server:
  port: 9999
magic-api:
  web: /magic/web #配置web页面入口
  resource: #配置存储方式
    #location: D:/expdir/xiaomai-magic-api #配置文件存储位置。当以classpath开头时，为只读模式#mac用户请改为可读写的目录#如果不想存到文件中，可以参考配置将接口信息存到数据库、Redis中（或自定义）  
    type: database # 配置存储在数据库中
    tableName: magic_api_file # 数据库中的表名
    #datasource: magic #指定数据源（单数据源时无需配置，多数据源时默认使用主数据源，如果存在其他数据源中需要指定。）
    prefix: /magic-api # key前缀
    readonly: false # 是否是只读模式  
  backup: #备份相关配置
    enable: true #是否启用
    max-history: -1 #备份保留天数，-1为永久保留
    #datasource: magic  #指定数据源（单数据源时无需配置，多数据源时默认使用主数据源，如果存在其他数据源中需要指定。）
    table-name: magic_api_backup #使用数据库存储备份时的表名
  task:
    thread-name-prefix: magic-task- #线程池名字前缀
    pool:
        size: 8 #线程池大小，默认值为CPU核心数
    shutdown:
        awaitTermination: false #关闭时是否等待任务执行完毕，默认为false
        awaitTerminationPeriod: 10s # 关闭时最多等待任务执行完毕的时间
  security:
    username: admin # 登录用的用户名
    password: 123456 # 登录用的密码
  editor-config: classpath:./magic-editor-config.js
    
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/magic-api-test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: mysql
  redis:
    host: 127.0.0.1
    port: 6379
    database: 4
    password: 
        