
package com.sap.document.sap.soap.functions.mc_style;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZFII00_JGJS_WS", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZFII00JGJSWS {


    /**
     * 
     * @param input
     * @param zfname
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ZFII00_JGJS_WS")
    @WebResult(name = "OUTPUT", targetNamespace = "")
    @RequestWrapper(localName = "ZFII00_JGJS_WS", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZFII00JGJSWS_Type")
    @ResponseWrapper(localName = "ZFII00_JGJS_WSResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZFII00JGJSWSResponse")
    public String zfii00JGJSWS(
            @WebParam(name = "INPUT", targetNamespace = "")
                    String input,
            @WebParam(name = "ZFNAME", targetNamespace = "")
                    String zfname);

}
