
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZFII00_JGJS_WS", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/C:/Users/wangfeng/Desktop/erp.wsdl")
public class ZFII00JGJSWS_Service
    extends Service
{

    private final static URL ZFII00JGJSWS_WSDL_LOCATION;
    private final static WebServiceException ZFII00JGJSWS_EXCEPTION;
    private final static QName ZFII00JGJSWS_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZFII00_JGJS_WS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/wangfeng/Desktop/erp.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZFII00JGJSWS_WSDL_LOCATION = url;
        ZFII00JGJSWS_EXCEPTION = e;
    }

    public ZFII00JGJSWS_Service() {
        super(__getWsdlLocation(), ZFII00JGJSWS_QNAME);
    }

    public ZFII00JGJSWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZFII00JGJSWS_QNAME, features);
    }

    public ZFII00JGJSWS_Service(URL wsdlLocation) {
        super(wsdlLocation, ZFII00JGJSWS_QNAME);
    }

    public ZFII00JGJSWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZFII00JGJSWS_QNAME, features);
    }

    public ZFII00JGJSWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZFII00JGJSWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZFII00JGJSWS
     */
    @WebEndpoint(name = "ZFII00_JGJS_WS")
    public ZFII00JGJSWS getZFII00JGJSWS() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZFII00_JGJS_WS"), ZFII00JGJSWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZFII00JGJSWS
     */
    @WebEndpoint(name = "ZFII00_JGJS_WS")
    public ZFII00JGJSWS getZFII00JGJSWS(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZFII00_JGJS_WS"), ZFII00JGJSWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZFII00JGJSWS_EXCEPTION!= null) {
            throw ZFII00JGJSWS_EXCEPTION;
        }
        return ZFII00JGJSWS_WSDL_LOCATION;
    }

}
