# 公共配置
spring:
  profiles:
    active: dev
  application:
      name: nacos-swagger

#开启端点  actuator
management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"  #开启actuator全部端点      http://IP:PORT/actuator


---
# 开发环境
server:
  port: 10013
spring:
  profiles: dev
  servlet: /
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:48848

---
# 测试环境
server:
  port: 11013
spring:
  profiles: test
  servlet: /
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:48848

---
# 生产环境
server:
  port: 12013
spring:
  profiles: prod
  servlet: /
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:48848
